export const varsomMockData = [
  {
    RegId: 10928,
    PreviousWarningRegId: 10927,
    RegionId: 3007,
    RegionName: "Vest-Finnmark",
    RegionTypeId: 10,
    RegionTypeName: "A",
    CountyList: [
      {
        Id: "fylkesnr",
        Name: "fylkesnavn",
      },
    ],
    MunicipalityList: [
      {
        Id: "kommunenr",
        Name: "kommunenavn",
      },
    ],
    UtmEast: 786087,
    UtmNorth: 7803739,
    UtmZone: 33,
    ValidFrom: "24/11/2017 00:00:00",
    ValidTo: "24/11/2017 23:59:59",
    NextWarningTime: "25/11/2017 16:00:00",
    PublishTime: "24/11/2017 08:19:39",
    DangerLevel: 4,
    DangerLevelName: "4 Stor",
    MainText: "Hovedbudskap (norsk)",
    Author: "anders@nve",
    AvalancheDanger: "Snøskredfare",
    EmergencyWarning: "Ikke gitt",
    SnowSurface: "Snøoverflate",
    CurrentWeaklayers: "Relevante svake lag",
    LatestAvalancheActivity: "Skredaktivitet (siste 3 døgn)",
    LatestObservations: "Andre relevante observasjoner (siste 3 døgn)",
    AvalancheProblems: [
      {
        AvalancheTypeId: 10,
        AvalancheTypeName: "Flakskred",
        AvalancheProblemTypeId: 30,
        AvalancheProblemTypeName: "Vedvarende svakt lag",
        AvalancheExtId: 15,
        AvalancheExtName: "Våte løssnøskred",
        AvalCauseId: 21,
        AvalCauseName: "Snødeket gjennomfuktet og ustabilt fra overflaten",
        DestructiveSizeExtId: 6,
        DestructiveSizeExtName: "Store",
        AvalProbabilityId: 7,
        AvalProbabilityName: "Meget sannsynlig",
        AvalTriggerSimpleId: 21,
        AvalTriggerSimpleName: "Liten tilleggsbelastning",
        AvalPropagationId: 3,
        AvalPropagationName: "Mange bratte heng",
        ExposedHeightFill: 1,
        ExposedHeight1: 600,
        ExposedHeight2: 0,
        ValidExpositions: 10000011,
      },
    ],
    MountainWeather: {
      LastSavedTime: "24/11/2017 08:19:39",
      Comment: "Kommentar om fjellvær",
      CloudCoverId: 20,
      CloudCoverName: "Klarvær",
      MeasurementTypes: {
        MeasurementType: {
          Id: 20,
          Name: "Vind",
          SortOrder: 20,
          MeasurementSubTypes: {
            MeasurementSubType: {
              Id: 20,
              Name: "Styrke",
              SortOrder: 20,
              Value: "Sterk kuling",
            },
          },
        },
      },
    },
    AvalancheAdvices: [
      {
        AdviceID: 1,
        ImageUrl:
          "https://api01.nve.no/hydrology/forecast/avalanche/v5.0.0/Images/AvalancheAdvice/1.jpg",
        Text:
          "Våt overflate: Unngå ferdsel i terreng brattere enn 30 grader. Unngå også utløpssoner.",
      },
    ],
  },
  {
    RegId: 10928,
    PreviousWarningRegId: 10927,
    RegionId: 3007,
    RegionName: "Vest-Finnmark",
    RegionTypeId: 10,
    RegionTypeName: "A",
    CountyList: [
      {
        Id: "fylkesnr",
        Name: "fylkesnavn",
      },
    ],
    MunicipalityList: [
      {
        Id: "kommunenr",
        Name: "kommunenavn",
      },
    ],
    UtmEast: 786087,
    UtmNorth: 7803739,
    UtmZone: 33,
    ValidFrom: "25/11/2017 00:00:00",
    ValidTo: "25/11/2017 23:59:59",
    NextWarningTime: "26/11/2017 16:00:00",
    PublishTime: "25/11/2017 08:19:39",
    DangerLevel: 3,
    DangerLevelName: "3 Betydelig",
    MainText: "Hovedbudskap (norsk)",
    Author: "anders@nve",
    AvalancheDanger: "Snøskredfare",
    EmergencyWarning: "Ikke gitt",
    SnowSurface: "Snøoverflate",
    CurrentWeaklayers: "Relevante svake lag",
    LatestAvalancheActivity: "Skredaktivitet (siste 3 døgn)",
    LatestObservations: "Andre relevante observasjoner (siste 3 døgn)",
    AvalancheProblems: [
      {
        AvalancheTypeId: 10,
        AvalancheTypeName: "Flakskred",
        AvalancheProblemTypeId: 30,
        AvalancheProblemTypeName: "Vedvarende svakt lag",
        AvalancheExtId: 15,
        AvalancheExtName: "Våte løssnøskred",
        AvalCauseId: 21,
        AvalCauseName: "Snødeket gjennomfuktet og ustabilt fra overflaten",
        DestructiveSizeExtId: 6,
        DestructiveSizeExtName: "Store",
        AvalProbabilityId: 7,
        AvalProbabilityName: "Meget sannsynlig",
        AvalTriggerSimpleId: 21,
        AvalTriggerSimpleName: "Liten tilleggsbelastning",
        AvalPropagationId: 3,
        AvalPropagationName: "Mange bratte heng",
        ExposedHeightFill: 1,
        ExposedHeight1: 600,
        ExposedHeight2: 0,
        ValidExpositions: 10000011,
      },
    ],
    MountainWeather: {
      LastSavedTime: "24/11/2017 08:19:39",
      Comment: "Kommentar om fjellvær",
      CloudCoverId: 20,
      CloudCoverName: "Klarvær",
      MeasurementTypes: {
        MeasurementType: {
          Id: 20,
          Name: "Vind",
          SortOrder: 20,
          MeasurementSubTypes: {
            MeasurementSubType: {
              Id: 20,
              Name: "Styrke",
              SortOrder: 20,
              Value: "Sterk kuling",
            },
          },
        },
      },
    },
    AvalancheAdvices: [
      {
        AdviceID: 1,
        ImageUrl:
          "https://api01.nve.no/hydrology/forecast/avalanche/v5.0.0/Images/AvalancheAdvice/1.jpg",
        Text:
          "Våt overflate: Unngå ferdsel i terreng brattere enn 30 grader. Unngå også utløpssoner.",
      },
    ],
  },
];
